### ISSUE TITLE
Main view renders a list of books 

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/Alexandria#2]

**Comment by hawkw** [comment]
I guess this depends on correct handling of the GET /books/ route. I need to make a backend issue for that.

**Comment by hawkw** [comment]
@redbassett implemented this because he is MY FAVOURITE PERSON EVER

**Comment by redbassett** [comment]
Fixed in 1408c580cdf67141e483e7f86b581114da7723f0.

**Comment by hawkw** [comment]
> Fixed in 1408c58. 

YEAH IT IS
