### ISSUE TITLE
Decide on UI library

### ISSUE THREAD

**Issue by hawkw** [alexandrialibrary/Alexandria#27]
Do we want to: 
  + use Bootstrap
  + use Polymer/Paper
  + use something else entirely
  + roll it ourselves

@redbassett gets the final say on this.

**Comment by hawkw** [comment]
Here's [Bootstrap/Angular integration](http://mgcrea.github.io/angular-strap/) that might be worthy of consideration?

**Comment by redbassett** [comment]
Polymer or Angularstrap

**Comment by hawkw** [comment]
You pick. :)

**Comment by redbassett** [comment]
Polymer.
