### ISSUE TITLE
Make application name available to frontend

### ISSUE THREAD

**Issue by redbassett** [alexandrialibrary/Alexandria#37]
Pass application name to front end dynamically from config.

**Comment by hawkw** [comment]
Okay. Config file will need to be implemented first (#29).

**Comment by hawkw** [comment]
See 21ffed4b69928412525dd4efd871967258c8d616. Page title is passed to templates. 

Currently, it's just passing "Alexandria" (and will pass "Alexandria Admin" on the admin control) because there's no config file to load title and other branding from. But later we'll do that.

**Comment by redbassett** [comment]
Fixed in 21ffed4b69928412525dd4efd871967258c8d616.
