### ISSUE TITLE
"It can handle any ISBN you throw at it" is a lie

### ISSUE THREAD

**Issue by redbassett** [alexandrialibrary/Alexandria#42]
1484206363

**Comment by hawkw** [comment]
oh my god

**Comment by hawkw** [comment]
This one is Not My Fault, the error is because the OpenLibrary API request for this ISBN is returning `{}`. See https://openlibrary.org/api/books?bibkeys=ISBN:1484206363&format=json&jscmd=data.

We should probably make a better error response, though. But this book appears to be the Null Book.

**Comment by hawkw** [comment]
(with that said there should be validation of OpenLibrary response JSON wads but _whatever_)

**Comment by hawkw** [comment]
As of a2cf652 `Book.fromJson()` is now in the `Try[T]` monad, so if we get an unparseable response object back from OpenLibrary, we should return an HTTP error code with a useable error message rather than attempting to serialise an entire Scalate error page as JSON.
